import React from "react";
import { useParams } from "react-router-dom";

const FetchData = props => {
  const params = useParams();
  return (
    <div className="bg-red-100">
      <h1>Start {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
      <h1>FetchData {params.id}</h1>
    </div>
  );
};

export default FetchData;
