# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
    
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Make Build
        run: npm run build
        env:
          REACT_APP_FB_KEY: ${{ secrets.FIREBASE_API_KEY }}
          REACT_APP_FB_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          REACT_APP_FB_DB_URL: ${{ secrets.FIREBASE_DB_URL }}
          REACT_APP_FB_PROJ_ID: ${{ secrets.FIREBASE_PROJ_ID }}
          REACT_APP_FB_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
            name: build
            path: build
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download artifacts
        uses: actions/download-artifact@master
        with:
          name: build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env: 
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
